Comparison and Shifts with Literals
mvcisback/py-aiger-bv pull request #12
Opened 2019-02-09 00:42 UTC by jzhang919

Added Features:

+ UnsignedBVExpr now supports left and logical right shifts. Also supports unsigned comparisons with literals.
+ SignedBVExpr now supports left and arithmetic right shifts. Also supports signed comparisons with literals. 

+ Added tests in test_expr.py to confirm correctness of all added operators.

2019-02-13 03:01 UTC, mvcisback requested changes
Overall, looks like a very good step in the right direction.

I made some comments in my code review for requested changes.

I apologize that the continuous integration seems to be broken at the moment. flake8 updated their API in a breaking way and I didn't pin the version......

2019-02-13 03:01 UTC, mvcisback commented on aigerbv/common.py
> +	return str(uuid1())
Is there a reason to change the indentation? I would prefer to stick to 4 spaces since that's what I've used throughout.

2019-02-13 03:01 UTC, mvcisback commented on aigerbv/common.py
> +	return str(uuid1())
Also, it makes the pull-request unreadable..

2019-02-13 03:01 UTC, mvcisback commented on aigerbv/expr.py
> +	wordlen = expr.size + n_bits if gate == cmn.left_shift_gate else expr.size
Hmm, I guess there's an implicit question about semantics here.

I personally don't think left shift should add extra bits, but rather have the bits "fall off the end". This matches most implementations of word level shift that I have seen.

2019-02-13 03:01 UTC, mvcisback commented on aigerbv/expr.py
> +	wordlen = expr.size + n_bits if gate == cmn.left_shift_gate else expr.size
Also, given the above comments, one could just have:

```python
from functools import partial

def _shift_gate(gate, expr, n_bits):
    return _unary_gate(gate=partial(gate, shift=n_bits), expr=expr)
```

2019-02-13 03:01 UTC, mvcisback commented on aigerbv/expr.py
> +import inspect
Did you forget to commit that code that use this? presumably it's for testing literals?

2019-02-13 22:33 UTC, jzhang919 commented on aigerbv/common.py
> +	return str(uuid1())
Will revert. Change was due to my auto style-checker script; will ensure that 4 spaces are used in the future. 👍

2019-02-13 22:46 UTC, jzhang919 commented on aigerbv/expr.py
> +	wordlen = expr.size + n_bits if gate == cmn.left_shift_gate else expr.size
Sounds good. Will commit new version where left shifts will have bits "fall off the end," e.g
0b111 << 1 = 0b110.

2019-02-13 22:47 UTC, jzhang919 commented on aigerbv/expr.py
> +import inspect
Will remove. I used inspect for checking class type in some other tests I created to better understand the aiger functions.

2019-02-14 11:23 UTC, mvcisback requested changes
Looks good! Just fix the flake8 issues so the continuous integration passes and I will merge.

2019-02-15 20:51 UTC, mvcisback approved these changes

2019-02-15 20:51 UTC, merged